# Generated by Django 4.0.3 on 2022-03-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('t', 'Tiny'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], default='s', max_length=6),
        ),
    ]
