# Generated by Django 4.0.3 on 2022-03-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_breed_size'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='breed',
            constraint=models.CheckConstraint(check=models.Q(('friendliness__gte', 1), ('friendliness__lte', 5)), name='A friendly value between 1-5'),
        ),
    ]
